import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/src/components/providers/query-provider";
import SessionProviderWrapper from "@/src/components/providers/session-provider";
import Header from "@/src/components/site/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-white text-neutral-900`}>
        <SessionProviderWrapper>
          <QueryProvider>
            <Header />
            <main className="mx-auto max-w-screen-xl px-4 sm:px-6 lg:px-8 py-6">
              {children}
            </main>
          </QueryProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
